version: "3"

services:
    namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop3.3.1-java8
        container_name: namenode
        volumes:
            - namenode:/hadoop/dfs/name
        environment:
            - CLUSTER_NAME=test
        env_file:
            - ./hadoop-hive.env
        ports:
            - "50070:50070"
            - 9010:9000
    datanode:
        image: bde2020/hadoop-datanode:2.0.0-hadoop3.3.1-java8
        container_name: datanode
        volumes:
            - datanode:/hadoop/dfs/data
        env_file:
            - ./hadoop-hive.env
        environment:
            SERVICE_PRECONDITION: "namenode:50070"
        ports:
            - "50075:50075"
    resourcemanager:
        image: bde2020/hadoop-resourcemanager:2.0.0-hadoop3.3.1-java8
        container_name: resourcemanager
        restart: always
        environment:
            SERVICE_PRECONDITION: "namenode:50070 namenode:9000 datanode:50075"
        env_file:
            - ./hadoop.env
    nodemanager1:
        image: bde2020/hadoop-nodemanager:2.0.0-hadoop3.3.1-java8
        container_name: nodemanager
        restart: always
        environment:
            SERVICE_PRECONDITION: "namenode:9000 namenode:50070 datanode:50075 resourcemanager:8088"
        env_file:
            - ./hadoop.env
    historyserver:
        image: bde2020/hadoop-historyserver:2.0.0-hadoop3.3.1-java8
        container_name: historyserver
        restart: always
        environment:
            SERVICE_PRECONDITION: "namenode:9000 namenode:50070 datanode:50075 resourcemanager:8088"
        volumes:
            - hadoop_historyserver:/hadoop/yarn/timeline
        env_file:
            - ./hadoop.env            
    hive-server:
        image: bde2020/hive:3.1.2-postgresql-metastore
        container_name: hive-server
        env_file:
            - ./hadoop-hive.env
        environment:
            HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
            SERVICE_PRECONDITION: "hive-metastore:9083"
        ports:
            - "10000:10000"
    hive-metastore:
        image: bde2020/hive:3.1.2-postgresql-metastore
        container_name: hive-metastore
        env_file:
            - ./hadoop-hive.env
        command: /opt/hive/bin/hive --service metastore
        environment:
            SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
        ports:
            - "9083:9083"
    hive-metastore-postgresql:
        image: bde2020/hive-metastore-postgresql:3.1.0-postgresql9.6.22
        environment: 
            POSTGRES_PASSWORD: "password"
        volumes: 
            - pgdata:/var/lib/postgresql/data  
    presto-coordinator:
        image: shawnzhu/prestodb:0.181
        ports:
            - "8090:8090"
    spark-master:
        image: bde2020/spark-master:3.1.2-hadoop3.2
        container_name: spark-master
        ports:
            - "8080:8080"
            - "7077:7077"
        environment:
            - INIT_DAEMON_STEP=setup_spark
    spark-worker-1:
        image: bde2020/spark-worker:3.1.2-hadoop3.2
        container_name: spark-worker-1
        depends_on:
            - spark-master
        ports:
            - "8081:8081"
        environment:
            - "SPARK_MASTER=spark://spark-master:7077"
    spark-worker-2:
        image: bde2020/spark-worker:3.1.2-hadoop3.2
        container_name: spark-worker-2
        depends_on:
            - spark-master
        ports:
            - "8082:8081"
        environment:
            - "SPARK_MASTER=spark://spark-master:7077"  
volumes:
    namenode:
    datanode:
    hadoop_historyserver:
    pgdata:    
networks: 
    default:
        name: test
